---
title: "Tidying data"
format: html
editor: visual
---

Setup

```{r}

library(tidyverse)
library(here)
library(qs)


#model functions
source("src/dir.R")
source("src/model_functions.R")


#species of interest

species <- c("atlantic_salmon", 
             "general_salmonid", 
             "european_seabass", 
             "gilthead_seabream", 
             "large_yellow_croaker", 
             "japanese_seabass",
             "japanese_amberjack",
             "general_grouper",
             "pompano",
             "milkfish")



```

Make repo structure

```{r}

create_repo(this_path = here())


```

Make input and output folder structure for species of interest

```{r}


#deploy data folder structure for species 

map(.x = species, .f = create_species_folders)


```

Pull in mariculture locations data from Clawson et al 2022 and save the species groups of interest

```{r}


farm_locations <- read.csv(file.path(rdsi_dir, "raw_data/aquaculture-locations/all_marine_aquaculture_farms_sources_final.csv")) |> 
  filter(species_group %in% c("Salmonidae fish", "General marine fish"))

qsave(x = farm_locations, file = "data/_general_data/farm_locations.qs") 

```

Modify Feed characterisation

```{r}

Food_charactisation_list <- 
  read_csv("data/_general_data/diets/protein_lipid_carb_summaries.csv") |> 
  select(-c(5)) |> 
  pivot_longer(names_to = "nutrient", values_to = "prop", cols = -species) |> 
  group_by(species) |> 
  group_split()


map(.x = Food_charactisation_list, .f = \(this_species_food){
  
  this_species <- this_species_food$species |> unique()
  
  this_species_food_df <- 
    this_species_food |> 
    relocate(prop, .before = "nutrient") |> 
    mutate(nutrient = as.character(paste0(str_to_sentence(nutrient), "s"))) |> 
    mutate(prop = as.double(prop)) |> 
    select(-species)
  
  write.table(this_species_food_df, file = sprintf("data/%s/forcings/Food_characterization.csv", this_species), row.names = FALSE, col.names = FALSE, sep = ",")

})



```



