---
title: "Formulating experimental feeds"
author: Tormey Reimer
date: today
format: html
editor: source
---

```{r setup}
#| code-summary: R setup

library(tidyverse)
library(conflicted)
library(here)
library(qs2)
conflicts_prefer(dplyr::filter(), dplyr::select(), .quiet = T)

here("00_model_functions.R") %>% source()
here("00_dirs.R") %>% source()
```

# Import ingredients and feeds

``` {r import-ingredients}
#| code-summary: Ingredient details

ingreds <- file.path(data_path, "all_ingredients.csv") %>% 
  read.csv() %>% 
  mutate(ingredient = as.factor(ingredient))
```

``` {r import-feeds}
#| code-summary: Feed compositions

feed_inputs <- file.path(data_path, "all_feeds.csv") %>% 
  read.csv() %>% 
  pivot_longer(names_to = "feed", values_to = "proportion", cols = !contains(c("ingredient", "proportion"))) %>% 
  mutate(feed = as.factor(feed),
         ingredient = as.factor(ingredient)) 
```

# Formulate feeds

```{r formulate-feeds}
#| code-summary: Format feeds as lists to feed into targets

all_feeds <- formulate_feeds(ingreds, feed_inputs)
```

```{r save-feeds}
qd_save(all_feeds, file.path(output_path, "feed_params.qs"))
```

