---
title: "Atlantic salmon model"
format: html
editor: visual
---

Setup

```{r}
library(tidyverse)
library(terra)
library(qs)
library(here)
library(sf)

#functions
source(here("src/model_functions.R"))

#species paths
this_species <- "atlantic_salmon"
this_path <- sprintf(here("data/%s"), this_species)


```

Prep temperature forcings for each farm site

```{r}

production_cycle <- read_csv("data/_general_data/production_cycles/production_cycle.csv") |> filter(species == this_species) |> rename(production_cycle_length = days)|> pull(production_cycle_length)


farms <-  qread("data/_general_data/farm_locations/locations_w_species_fao_area_stocking.qs") |> 
  filter(model_name == this_species) |> 
  select(-row_num) |> 
  mutate(farm_id = row_number())


days <- seq(1:production_cycle)


temp_data <- map_dfc(.x = days, .f = \(day_number){
  
  rast_day_number <- if_else(day_number <= 365, true = day_number, false = day_number-365)
  
  message("Getting temperature data for all sites for ", this_species,  " - day ", day_number)
  
  sst_test <- rast(sprintf("data/_general_data/SST/SST_gf_rasters/sst_nasa_mur_L4_0.25_mean2010-2019_day_%s.tif", rast_day_number))

  extract(sst_test, farms) |> 
    mutate(day = paste0("day_", day_number)) |> 
    pivot_wider(names_from = "day", values_from = "focal_mean") |> 
    select(-ID)
  
  
}) |> 
  mutate(farm_id = row_number())


farms_w_temp_df <- 
  farms |> 
  left_join(temp_data, by = c("farm_id" = "farm_id")) |> 
  pivot_longer(names_to = "day", values_to = "temp_c", cols = starts_with("day_"))


head(farms_w_temp_df)

qsave(x = farms_w_temp_df, file = sprintf("data/_general_data/farm_locations/%s_locations_w_temps.qs", this_species))


farm_list <- 
  farms_w_temp_df |>
  group_by(farm_id) |> 
  group_split()


#save temperature forcings per farm

future::plan(strategy = "multisession", workers = parallel::detectCores()-2) #select multiple cores

furrr::future_map(.x = farm_list, .f = \(this_farm){
  
  this_farm_id <- unique(this_farm$farm_id)
  
  temp_data_only <- 
    this_farm |> 
    select(day, temp_c) |> 
    st_drop_geometry()
  
  
  saveName <- sprintf("data/%s/forcings/Water_temperature_farmID_%s.csv", this_species, this_farm_id)
  
  if(!file.exists(saveName)){
    
     write.table(x = temp_data_only, file = saveName, col.names = FALSE, row.names = FALSE, sep = ",")
  }
    
})





```

Run model for each location under reference feed.

```{r}

farm_list <- 
  qread(file = sprintf("data/_general_data/farm_locations/%s_locations_w_temps.qs", this_species)) |> 
  filter(model_name == this_species) |> 
  group_by(farm_id) |> 
  group_split()
    

#test 
this_farm <- farm_list[[1]]


map(.x = farm_list, .f = \(this_farm){
  
  these_temps <- this_farm$temp_c
  
  this_stocking_N = unique(round(this_farm$stocking_n))
  
  this_farm_id <- unique(paste0("farmID_", this_farm$farm_id))
  
  forcings <- data_loader(this_path =  this_path, this_farm_id = this_farm_id)
  
  out_pre <- preprocess(this_path = this_path, these_forcings = forcings, this_feed = "reference", this_stocking_N = this_stocking_N)
  
 
  
  out_RK_solver <- loop(Param, Tint, Food, IC, times, N, this_path = this_path)
  
  
})








model_output <- model(this_path = this_path, forcings = inputs, this_species = this_species)

forcings

Pop_matrix




```

```{r}
Spp_param=out_pre[[1]]
Pop_param=out_pre[[2]]
Tint=out_pre[[3]]
#Gint=out_pre[[3]]
Food=out_pre[[4]]
IC=out_pre[[5]]
times=out_pre[[6]]
Dates=out_pre[[7]]
N=out_pre[[8]]
CS=out_pre[[9]]

Path = this_path




ind_equations <- function(Path, Pop_param, Spp_param, Temp, Food, times, N){
  
  
  # Parameters definition
  ingmax=rnorm(1, mean = Pop_param[4], sd = Pop_param[5])     # [g/d] Maximum ingestion rate
  alpha=Spp_param[2]         # [-] Feeding catabolism coefficient
  betaprot=Spp_param[3]      # [-] Assimilation coefficient for protein
  betalip=Spp_param[4]       # [-] Assimilation coefficient for lipid
  betacarb=Spp_param[5]      # [-] Assimilation coefficient for carbohydrates
  epsprot=Spp_param[6]       # [J/gprot] Energy content of protein
  epslip=Spp_param[7]        # [J/glip] Energy content of lipid
  epscarb=Spp_param[8]       # [J/gcarb] Energy content of carbohydrate
  epsO2=Spp_param[9]         # [J/gO2] Energy consumed by the respiration of 1g of oxygen
  pk=Spp_param[10]           # [1/day] Temperature coefficient for the fasting catabolism
  k0=Spp_param[11]           # [1/Celsius degree]  Fasting catabolism at 0 Celsius degree
  m=Spp_param[12]            # [-] Weight exponent for the anabolism
  n=Spp_param[13]            # [-] Weight exponent for the catabolism
  betac=Spp_param[14]        # [-]  Shape coefficient for the H(Tw) function
  Tma=Spp_param[15]          # [Celsius degree] Maximum lethal temperature for Dicentrarchus labrax
  Toa=Spp_param[16]          # [Celsius degree] Optimal temperature for Dicentrarchus labrax
  Taa=Spp_param[17]          # [Celsius degree] Lowest feeding temperature for Dicentrarchus labrax
  omega=Spp_param[18]        # [gO2/g] Oxygen consumption - weight loss ratio
  a=Spp_param[19]            # [J/gtissue] Energy content of fish tissue
  k=Spp_param[20]            # [-] Weight exponent for energy content
  eff=Spp_param[21]          # [-] Food ingestion efficiency
  
  # Food composition definition
  Pcont=Food[1]       # [-] Percentage of proteins in the food
  Lcont=Food[2]       # [-] Percentage of lipids in the food
  Ccont=Food[3]       # [-] Percentage of carbohydrates in the food
  
  # Weight and resource
  ti = times[1]
  tf = times[2]                                 # number of days 
  dt = times[3]                               # time step
  # isave = 1
  # nsave  <- floor(tmax/(dt*isave)) # no. of time slots to save
  days<-(1:tf)*dt
  
  weight <- rep(0,nsave)
  weight[ti]<- rnorm(1, mean = Pop_param[1], sd = Pop_param[2]) # start size in grams
  # 
  # # vectors of the other important growth metrics: intake, functional response, assimilated energy and growth increment
  fgT <- rep(0, nsave)
  frT <- rep(0, nsave)
  Tfun <- rep(0, nsave)
  ing <- rep(0, nsave)
  resource <- rep(0, nsave)
  G <- rep(0, nsave)
  ingvero <- rep(0, nsave)
  epstiss <- rep(0, nsave)
  assE <- rep(0, nsave)
  Pexc <- rep(0, nsave)
  Lexc <- rep(0, nsave)
  Cexc <- rep(0, nsave)
  exc <- rep(0, nsave)
  Pwst <- rep(0, nsave)
  Lwst <- rep(0, nsave)
  Cwst <- rep(0, nsave)
  wst <- rep(0, nsave)
  anab <- rep(0, nsave)
  catab <- rep(0, nsave)
  metab <- rep(0, nsave)
  O2 <- rep(0, nsave)
  NH4 <- rep(0, nsave)
  dw <- rep(0, nsave)
  
  # EQUATIONS
  for (i in 1:(nsave-1)){
    
  # Forcing temperature
  fgT[i]= exp(betac*(Temp[i]-Toa))*((Tma-Temp[i])/(Tma-Toa))^(betac*(Tma-Toa))   # Optimum Temperature dependence for ingestion
  frT[i]= exp(pk*Temp[i])                                                       # Exponential Temperature dependence for catabolism
  # Tfun[i]=cbind(fgT[i], frT[i])                                               # Output with temperature limitation functions
  
  # Ingested mass
  ing[i]=ingmax*(weight[i]^m)*fgT[i]   # [g/d] Potential ingestion rate
  resource[i] = 0.066*weight[i]^0.75 # this is taken from the salmon model
  G[i] = eff*resource[i]
  
  # # Lowest feeding temperature threshold
  if (Temp[i]<Taa) {
    ing=0
  }

  # reduced feeding at temps higher than optimal temp
  if (Temp[i]>Toa) {
    ing[i] = 0
  }
  
  # Available food limitation
  if (ing[i] > G[i]) {
    ingvero[i] = G[i]         # [g/d] Actual ingestion rate
  }  else {
    ingvero[i] = ing[i]     # [g/d] Actual ingestion rate
  }
  
  # Energy content of somatic tissue [J/g] Source: Lupatsch et al. (2003)
  epstiss[i] = a*weight[i]^k
  
  # Ingested energy
  diet = Pcont*epsprot*betaprot+Lcont*epslip*betalip+Ccont*epscarb*betacarb # [J/g] Energy content of the ingested food
  assE[i] = ingvero[i]*diet # [J/d] Ingested energy
  
  # Compute excretion (not sure if this is actually dissolved inorganic nutrients)
  Pexc[i] = (1-betaprot)*Pcont*ingvero[i]  # Excreted proteins [g/d]
  Lexc[i] = (1-betalip)*Lcont*ingvero[i]   # Excreted lipids [g/d]
  Cexc[i] = (1-betacarb)*Ccont*ingvero[i]  # Excreted carbohydrates [g/d]
  # exc[i]=cbind(Pexc[i],Lexc[i],Cexc[i])        # Output with excretion values
  
  # Compute waste (this is uneaten feed only - does not include solid faecal matter)
  Pwst[i]=((G[i]/eff)-ingvero[i])*Pcont     # Proteins to waste [g/d]
  Lwst[i]=((G[i]/eff)-ingvero[i])*Lcont     # Lipids to waste [g/d]
  Cwst[i]=((G[i]/eff)-ingvero[i])*Ccont     # Carbohydrates to waste [g/d]
  # wst[i]=cbind(Pwst[i],Cwst[i],Lwst[i])        # Output with waste values
  
  # Metabolism terms
  anab[i]=assE[i]*(1-alpha)                    # Net anabolism [J/d]
  catab[i]=epsO2*k0*frT[i]*(weight[i]^n)*omega    # Fasting catabolism [J/d]
  # metab[i]=cbind(anab[i],catab[i])                # Output with metabolic rates
  
  # O2 and NH4 produced
  O2[i]=catab[i]/epsO2          # O2 consumed [g02/d]
  NH4[i]=O2[i]*0.06             # NH4 produced [gN/d]
  
  # Mass balance
  dw[i] = (anab[i]-catab[i])/epstiss[i] # weight increment [g/d]
  
  weight[i+1] = weight[i] + dw[i]*dt
  }
  # Function outputs
  output=cbind(days, weight, biomass = weight*N[ti:tf], dw, epstiss, Pexc_total = Pexc*N[ti:tf], Lexc_total = Lexc*N[ti:tf], Cexc_total = Cexc*N[ti:tf], Pwst_total = Pwst*N[ti:tf], Lwst_total = Lwst*N[ti:tf], Cwst_total = Cwst*N[ti:tf], ing_total = ing*N[ti:tf], ingvero_total = ingvero*N[ti:tf], anab, catab, O2, NH4_total = NH4*N[ti:tf], resource_total = resource*N[ti:tf], fgT, frT, Temp)
  return(output) 
}



loop <- function(Path, Pop_param, Spp_param, Temp, Food, times, N){

  #initiate matrices to fill for each population iteration
  
  weight_mat <- matrix(data = 0, nrow = nruns, ncol = tf)
  biomass_mat <- matrix(data = 0, nrow = nruns, ncol = tf)
  dw_mat <- matrix(data = 0, nrow = nruns, ncol = tf)
  epistiss_mat <- matrix(data = 0, nrow = nruns, ncol = tf)
  Pexc_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  Lexc_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  Cexc_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  Pwst_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  Lwst_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  Cwst_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  ingvero_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  anab_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  catab_mat <- matrix(data = 0, nrow = nruns, ncol = tf)
  O2_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  NH4_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  resource_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  fgT_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  frT_mat <- matrix(data = 0, nrow = nruns, ncol = tf) 
  
  
  for(n in 1:nruns){
    
    message("Running population for ", this_species, ",  ", this_farm_id, ", iteration ", n)
    
    ind_output <- ind_equations(Path = Path, Pop_param = Pop_param, Spp_param = Spp_param, Temp = Temp, Food = Food, times = times,N = N)
    
    #append to matrix
    weight_mat[n,] <- ind_output[,2]
    biomass_mat[n,] <- ind_output[,3]
    dw_mat[n,] <- ind_output[,4]
    epistiss_mat[n,] <- ind_output[,5]
    Pexc_mat[n,] <-  ind_output[,6]
    Lexc_mat[n,] <-  ind_output[,7]
    Cexc_mat[n,] <-  ind_output[,8]
    Pwst_mat[n,] <-  ind_output[,9]
    Lwst_mat[n,] <-  ind_output[,10]
    Cwst_mat[n,] <-  ind_output[,11]
    ingvero_mat[n,] <-  ind_output[,13]
    anab_mat[n,] <-  ind_output[,14]
    catab_mat[n,] <-  ind_output[,15]
    O2_mat[n,] <-  ind_output[,16]
    NH4_mat[n,] <-  ind_output[,17]
    resource_mat[n,] <- ind_output[,18]
    fgT_mat[n,] <-  ind_output[,19]
    frT_mat[n,] <-  ind_output[,20]
    
  }
  
  weight_stat = cbind(colMeans(weight_mat), colSds(weight_mat))
  biomass_stat = cbind(colMeans(biomass_mat), colSds(biomass_mat))
  dw_stat = cbind(colMeans(dw_mat), colSds(dw_mat))
  epistiss_stat = cbind(colMeans(epistiss_mat), colSds(epistiss_mat))
  Pexc_stat = cbind(colMeans(Pexc_mat), colSds(Pexc_mat))
  Lexc_stat = cbind(colMeans(Lexc_mat), colSds(Lexc_mat))
  Cexc_stat = cbind(colMeans(Cexc_mat), colSds(Cexc_mat))
  Pwst_stat = cbind(colMeans(Pwst_mat), colSds(Pwst_mat))
  Lwst_stat = cbind(colMeans(Lwst_mat), colSds(Lwst_mat))
  Cwst_stat = cbind(colMeans(Cwst_mat), colSds(Cwst_mat))
  ingvero_stat = cbind(colMeans(ingvero_mat), colSds(ingvero_mat))
  anab_stat = cbind(colMeans(anab_mat), colSds(anab_mat))
  catab_stat = cbind(colMeans(catab_mat), colSds(catab_mat))
  O2_stat = cbind(colMeans(O2_mat), colSds(O2_mat))
  NH4_stat = cbind(colMeans(NH4_mat), colSds(NH4_mat))
  resource_stat = cbind(colMeans(resource_mat), colSds(resource_mat))
  fgT_stat = cbind(colMeans(fgT_mat), colSds(fgT_mat))
  frT_stat = cbind(colMeans(frT_mat), colSds(frT_mat))
  
  
  
  out_loop <- list(weight_stat, biomass_stat, dw_stat, 
                   epistiss_stat, 
                   Pexc_stat, Lexc_stat, Cexc_stat,
                   Pwst_stat, Lwst_stat, Cwst_stat, 
                   ingvero_stat, anab_stat, catab_stat,
                   O2_stat, NH4_stat, resource_stat,
                   fgT_stat, frT_stat)
  
  return(out_loop)
}








post_process <- function(this_path, this_farm_id, out_loop, times, Dates, N, CS) {
  
  cat('Data post-processing\n')
  cat('\n')
  
  ti=times[1]           # Integration beginning
  tf=times[2]           # Integration end
  
  # Extracts outputs from the output list
  W_stat=out_loop[[1]]
  Bio_stat = out_loop[[2]]
  Dw_stat = out_loop[[3]]
  Epistiss_stat = out_loop[[4]]
  Pexc_stat=out_loop[[5]]
  Lexc_stat=out_loop[[6]]
  Cexc_stat=out_loop[[7]]
   Pwst_stat=out_loop[[8]]
  Lwst_stat=out_loop[[9]]
  Cwst_stat=out_loop[[10]]
  Ingvero_stat=out_loop[[11]]
  A_stat=out_loop[[12]]
  C_stat=out_loop[[13]]
  NH4_stat=out_loop[[14]]
  O2_stat=out_loop[[15]]
  Resource_stat = out_loop[[16]]
  fgT_stat=out_loop[[17]]
  frT_stat=out_loop[[18]]

  
  # Adjusts results acoording with integration extremes
  # now day 1 coincides with ti
  
  
  # Days to commercial size
  
  # Lower bound
  foo <- function(w,S){which(w>S)[1]}
  arg=as.data.frame(W_stat[,1]-weight_stat[,2])
  days <- apply(arg,1,foo,S=CS)
  days_L <- as.data.frame(days)
  NonNAindex <- which(!is.na(days_L))
  if (length(NonNAindex)==0) {
    Lb_daysToSize="Not reaching the commercial size"
  }else{  Lb_daysToSize <- min(NonNAindex)
  }
  
  # Mean
  foo <- function(w,S){which(w>S)[1]}
  arg=as.data.frame(weight_stat[,1])
  days <- apply(arg,1,foo,S=CS)
  days_L <- as.data.frame(days)
  NonNAindex <- which(!is.na(days_L))
  if (length(NonNAindex)==0) {
    Mean_daysToSize="Not reaching the commercial size"
  }else{  Mean_daysToSize <- min(NonNAindex)
  }
  
  # Upper bound
  foo <- function(w,S){which(w>S)[1]}
  arg=as.data.frame(weight_stat[,1]+weight_stat[,2])
  days <- apply(arg,1,foo,S=CS)
  days_L <- as.data.frame(days)
  NonNAindex <- which(!is.na(days_L))
  if (length(NonNAindex)==0) {
    Ub_daysToSize="Not reaching the commercial size"
  }else{  Ub_daysToSize <- min(NonNAindex)
  }
  
  # List containing days to size
  daysToSize<-as.list(cbind(Ub_daysToSize,Mean_daysToSize,Lb_daysToSize))
  
  
  
  out_post = list(W_stat, Bio_stat, dw_stat, Epistiss_stat, Pexc_stat, Lexc_stat, Cexc_stat, Pwst_stat, Lwst_stat, Cwst_stat, A_stat, C_stat, NH4_stat,O2_stat,  Resource_stat, fgT_stat, frT_stat, daysToSize, N)
  
  
  
  
  # PLOT RESULTS
  #shorter and longer version of days due to lag being used in some functions
  
  days <- seq(from = ti, to = tf-1, by = 1) # create a dates vector to plot results
  days2 <- seq(ti, by = 1, length = tf-ti+1) # create a dates vector to plot results
  
  
  
  
  
  # Plot weight

  weight_df = data.frame(days = days2, weight = W_stat[,1], lower_bound = W_stat[,1]-W_stat[,2], upper_bound = W_stat[,1]+W_stat[,2])

#plot weight    
ggplot(data = weight_df)+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
    geom_line(aes(x = days, y = weight))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Weight (g)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))

ggsave(filename = file.path(this_path, sprintf("figures/outputs/weight_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")

  


  # plot biomass


biomass_df = data.frame(days = days2, biomass = Bio_stat[,1], lower_bound = Bio_stat[,1]-Bio_stat[,2], upper_bound = Bio_stat[,1]+Bio_stat[,2])

    
ggplot(data = biomass_df)+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
    geom_line(aes(x = days, y = biomass))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Total farm biomass (tonnes)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))+
  scale_y_continuous(labels = \(label) label/1e+6)

ggsave(filename = file.path(this_path, sprintf("figures/outputs/biomass_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")

  

  # plot dW


dw_df = data.frame(days = days, dw = Dw_stat[,1][-730], lower_bound = Dw_stat[,1][-730]-Dw_stat[,2][-730], upper_bound = Dw_stat[,1][-730]+Dw_stat[,2][-730])

    
ggplot(data = dw_df)+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
    geom_line(aes(x = days, y = dw))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = bquote(Delta~ Body~weight~g~day^1))+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))

ggsave(filename = file.path(this_path, sprintf("figures/outputs/dw_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")

  

#plot energy content of somatic tissue

epistiss_df = data.frame(days = days, epistiss = Epistiss_stat[,1][-730], lower_bound = Epistiss_stat[,1][-730]-Epistiss_stat[,2][-730], upper_bound = Epistiss_stat[,1][-730]+Epistiss_stat[,2][-730])

    
ggplot(data = epistiss_df)+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
    geom_line(aes(x = days, y = epistiss))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Energy content of somatic tissue (J/g)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))


ggsave(filename = file.path(this_path, sprintf("figures/outputs/epistiss_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")


# plot excretion

excretion_df <- 
  rbind(
  data.frame(days = days2, 
             mean_excretion = Pexc_stat[,1], 
             lower_bound = Pexc_stat[,1]-Pexc_stat[,2], 
             upper_bound = Pexc_stat[,1]+Pexc_stat[,2],
             nutrient = "Protein"),
  data.frame(days = days2, 
             mean_excretion = Lexc_stat[,1], 
             lower_bound = Lexc_stat[,1]-Lexc_stat[,2], 
             upper_bound = Lexc_stat[,1]+Lexc_stat[,2],
             nutrient = "Lipid"),
  data.frame(days = days2, 
             mean_excretion = Cexc_stat[,1], 
             lower_bound = Cexc_stat[,1]-Cexc_stat[,2], 
             upper_bound = Cexc_stat[,1]+Cexc_stat[,2],
             nutrient = "Carbohydrates")
  )


ggplot(data = excretion_df |> filter(days != 730))+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound, fill = nutrient), alpha = 0.2)+
  geom_line(aes(x = days, y = mean_excretion, colour = nutrient))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Excretion (kg/day)")+
  theme(text=element_text(size=8),
        legend.position = "inside",
        legend.title = element_blank(),
        legend.position.inside= c(0.2, 0.8),
        legend.background = element_rect(fill="transparent"))+
  scale_y_continuous(labels = \(label) label/1e+3)

ggsave(filename = file.path(this_path, sprintf("figures/outputs/excretion_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")


  # plot wasted feed

feed_waste_df <- 
  rbind(
  data.frame(days = days2, 
             mean_waste = Pwst_stat[,1], 
             lower_bound = Pwst_stat[,1]-Pwst_stat[,2], 
             upper_bound = Pwst_stat[,1]+Pwst_stat[,2],
             nutrient = "Protein"),
  data.frame(days = days2, 
             mean_waste = Lwst_stat[,1], 
             lower_bound = Lwst_stat[,1]-Lwst_stat[,2], 
             upper_bound = Lwst_stat[,1]+Lwst_stat[,2],
             nutrient = "Lipid"),
  data.frame(days = days2, 
             mean_waste = Cwst_stat[,1], 
             lower_bound = Cwst_stat[,1]-Cwst_stat[,2], 
             upper_bound = Cwst_stat[,1]+Cwst_stat[,2],
             nutrient = "Carbohydrates")
  )

ggplot(data = feed_waste_df |> filter(days != 730))+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound, fill = nutrient), alpha = 0.2)+
  geom_line(aes(x = days, y = mean_waste, colour = nutrient))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Feed waste (kg/day)")+
  theme(text=element_text(size=8),
        legend.position = "inside",
        legend.position.inside = c(0.25, 0.8),
        legend.background = element_rect(fill="transparent"),
        legend.title = element_blank())+
  scale_y_continuous(labels = \(label) label/1e+3)


ggsave(filename = file.path(this_path, sprintf("figures/outputs/feed_waste_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")



#plot ingestion


ingvero_df = data.frame(days = days, ingvero = Ingvero_stat[,1][-730], lower_bound = Ingvero_stat[,1][-730]-Ingvero_stat[,2][-730], upper_bound = Ingvero_stat[,1][-730]+Ingvero_stat[,2][-730])



ggplot(data = ingvero_df)+
  geom_ribbon(aes(x = days, ymin = lower_bound, ymax = upper_bound), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
    geom_line(aes(x = days, y = ingvero))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Ingestion (kg/day)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))+
  scale_y_continuous(labels = \(label) label/1e+3)


ggsave(filename = file.path(this_path, sprintf("figures/outputs/actual_ingestion_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")



```


```{r}
filepath=file.path(this_path,"/figures/outputs/wasted_feed.jpeg")
  jpeg(filepath,800,600)
  Lub=LwstSave[,1]+LwstSave[,2]
  Pub=PwstSave[,1]+PwstSave[,2]
  Cub=CwstSave[,1]+CwstSave[,2]
  Llb=as.matrix(matrix(0,nrow=length(Lub),ncol=1))
  Plb=as.matrix(matrix(0,nrow=length(Pub),ncol=1))
  Clb=as.matrix(matrix(0,nrow=length(Cub),ncol=1))
  for (i in 1:length(LwstSave[,1]-LwstSave[,2])){
    Llb[i]=max(LwstSave[i,1]-LwstSave[i,2],0)
    Plb[i]=max(PwstSave[i,1]-PwstSave[i,2],0)
    Clb[i]=max(CwstSave[i,1]-CwstSave[i,2],0)
  }
  maxub=max(Lub,Pub,Cub)
  plot(days,LwstSave[,1],ylab="Wasted feed (kg/d)", xlab=" ",xaxt = "n",type="l",cex.lab=1.4,col="red",ylim=c(0,maxub+0.05*maxub))
  polygon(c(days,rev(days)),c(Llb,rev(Lub)),col="grey75",border=FALSE)
  lines(days,LwstSave[,1],lwd=2,col="red")
  polygon(c(days,rev(days)),c(Plb,rev(Pub)),col="grey75",border=FALSE)
  lines(days,PwstSave[,1],lwd=2,col="green")
  polygon(c(days,rev(days)),c(Clb,rev(Cub)),col="grey75",border=FALSE)
  lines(days,CwstSave[,1],lwd=2,col="blue")
  labDates <- seq(as.Date(Dates[1], format = "%d/%m/%Y"), tail(days, 1), by = "months")
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  legend("topleft",c("Proteins","Lipids","Carbohydrates"),fill=c("red","green","blue"))
  dev.off()
  
  # plot ingested food
  filepath=file.path(this_path,"figures/outputs/actual_ingestion.jpeg")
  jpeg(filepath,800,600)
  ub=ingestionSave[,1]+ingestionSave[,2]
  lb=as.matrix(matrix(0,nrow=length(ub),ncol=1))
  for (i in 1:length(ingestionSave[,1]-ingestionSave[,2])){
    lb[i]=max(ingestionSave[i,1]-ingestionSave[i,2],0)
  }
  maxub=max(ingestionSave[,1]+ingestionSave[,2])
  plot(days,ingestionSave[,1],ylab="Ingested food (g)", xlab=" ",xaxt = "n",type="l",cex.lab=1.4,col="red",ylim=c(0,maxub+0.05*maxub))
  polygon(c(days,rev(days)),c(lb,rev(ub)),col="grey90",border=FALSE)
  lines(days,ingestionSave[,1],lwd=2,col="red")
  lines(days,lb,col="blue")
  lines(days,ub,col="blue")
  labDates <- seq(as.Date(Dates[1], format = "%d/%m/%Y"), tail(days, 1), by = "months")
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  dev.off()
  
  # plot limitation functions
  filepath=file.path(this_path,"figures/outputs/temperature_response.jpeg")
  jpeg(filepath,800,600)
  ub=max(max(fgT),max(frT))
  plot(days,fgT,ylab="Temperature response function",xlab=" ",xaxt = "n",cex.lab=1.4,col="red",type="l",ylim=c(0,ub+0.05*ub))
  lines(days,frT,col="blue")
  legend("topright",c("Anabolism","Catabolism"),fill=c("red","blue"))
  labDates <- seq(ti:tf)
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  dev.off()
  
  # plot metabolic rates
  filepath=file.path(this_path,"/figures/outputs/metabolism.jpeg")
  jpeg(filepath,800,600)
  Aub=ASave[,1]+ASave[,2]
  Cub=CSave[,1]+CSave[,2]
  Alb=as.matrix(matrix(0,nrow=length(Aub),ncol=1))
  Clb=as.matrix(matrix(0,nrow=length(Cub),ncol=1))
  for (i in 1:length(LwstSave[,1]-LwstSave[,2])){
    Alb[i]=max(ASave[i,1]-ASave[i,2],0)
    Clb[i]=max(CSave[i,1]-CSave[i,2],0)
  }
  maxub=max(Aub,Cub)
  plot(days,ASave[,1],ylab="Metabolic rates (J/d)", xlab=" ",xaxt = "n",type="l",cex.lab=1.4,col="red",ylim=c(0,maxub+0.05*maxub))
  polygon(c(days,rev(days)),c(Alb,rev(Aub)),col="grey75",border=FALSE)
  lines(days,ASave[,1],lwd=2,col="red")
  polygon(c(days,rev(days)),c(Clb,rev(Cub)),col="grey75",border=FALSE)
  lines(days,CSave[,1],lwd=2,col="blue")
  labDates <- seq(as.Date(Dates[1], format = "%d/%m/%Y"), tail(days, 1), by = "months")
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  legend("topleft",c("Anabolic rate","Catabolic rate"),fill=c("red","blue"))
  dev.off()
  
  # plot population dynamics
  filepath=file.path(this_path,"/figures/outputs/Population.jpeg")
  jpeg(filepath,800,600)
  plot(days2, N, ylab="Number of individuals", xlab="", xaxt = "n",type="l",cex.lab=1.4)
  labDates <- seq(as.Date(Dates[1], format = "%d/%m/%Y"), tail(days, 1), by = "months")
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  dev.off()
  
  # plot O2 consumption
  filepath=file.path(this_path,"/figures/outputs/O2_consumption.jpeg")
  jpeg(filepath,800,600)
  ub=O2Save[,1]+O2Save[,2]
  lb=as.matrix(matrix(0,nrow=length(ub),ncol=1))
  for (i in 1:length(O2Save[,1]-O2Save[,2])){
    lb[i]=max(O2Save[i,1]-O2Save[i,2],0)
  }
  maxub=max(O2Save[,1]+O2Save[,2])
  plot(days,O2Save[,1],ylab="O2 consumption (kgO2/d)", xlab=" ",xaxt = "n",type="l",cex.lab=1.4,col="red",ylim=c(0,maxub+0.05*maxub))
  polygon(c(days,rev(days)),c(lb,rev(ub)),col="grey90",border=FALSE)
  lines(days,O2Save[,1],lwd=2,col="red")
  lines(days,lb,col="blue")
  lines(days,ub,col="blue")
  labDates <- seq(as.Date(Dates[1], format = "%d/%m/%Y"), tail(days, 1), by = "months")
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  dev.off()
  
  # plot NH4 production
  filepath=file.path(this_path,"/figures/outputs/NH4_release.jpeg")
  jpeg(filepath,800,600)
  ub=NH4Save[,1]+NH4Save[,2]
  lb=as.matrix(matrix(0,nrow=length(ub),ncol=1))
  for (i in 1:length(NH4Save[,1]-NH4Save[,2])){
    lb[i]=max(NH4Save[i,1]-NH4Save[i,2],0)
  }
  maxub=max(NH4Save[,1]+NH4Save[,2])
  plot(days,NH4Save[,1],ylab="NH4 release (kgN/d)", xlab=" ",xaxt = "n",type="l",cex.lab=1.4,col="red",ylim=c(0,maxub+0.05*maxub))
  polygon(c(days,rev(days)),c(lb,rev(ub)),col="grey90",border=FALSE)
  lines(days,NH4Save[,1],lwd=2,col="red")
  lines(days,lb,col="blue")
  lines(days,ub,col="blue")
  labDates <- seq(as.Date(Dates[1], format = "%d/%m/%Y"), tail(days, 1), by = "months")
  axis.Date(side = 1, days, at = labDates, format = "%d %b %y", las = 2)
  dev.off()
  
  # Results save
  filepath=file.path(this_path,"/data_products/weight.csv")
  write.csv(weightSave,filepath)
  
  filepath=file.path(this_path,"data_products/faeces_production_Proteins.csv")
  write.csv(PexcSave,filepath)
  
  filepath=file.path(this_path,"/data_products/faeces_production_Lipids.csv")
  write.csv(LexcSave,filepath)
  
  filepath=file.path(this_path,"/data_products/faeces_production_Carbohydrates.csv")
  write.csv(CexcSave,filepath)
  
  filepath=file.path(this_path,"data_products/wasted_feed_Proteins.csv")
  write.csv(PwstSave,filepath)
  
  filepath=file.path(this_path,"/data_products/wasted_feed_Lipids.csv")
  write.csv(LwstSave,filepath)
  
  filepath=file.path(this_path,"/data_products/wasted_feed_Carbohydrates.csv")
  write.csv(CwstSave,filepath)
  
  filepath=file.path(this_path,"/data_products/actual_ingestion.csv")
  write.csv(ingestionSave,filepath)
  
  filepath=file.path(this_path,"/data_products/anabolic_rate.csv")
  write.csv(ASave,filepath)
  
  filepath=file.path(this_path,"/data_products/catabolic_rate.csv")
  write.csv(CSave,filepath)
  
  tfun=cbind(fgT,frT)
  
  filepath=file.path(this_path,"/data_products/temperature_response.csv")
  write.csv(tfun,filepath)
  
  filepath=file.path(this_path,"/data_products/O2_consumption.csv")
  write.csv(O2Save,filepath)
  
  filepath=file.path(this_path,"/data_products/NH4_release.csv")
  write.csv(NH4Save,filepath)
  
  filepath=file.path(this_path,"/data_products/population.csv")
  write.csv(N,filepath)
  
  filepath=file.path(this_path,"/data_products/Days_to_commercial_size.csv")
  write.csv(daysToSize,filepath)
  
  return(output)
  
}



















biomass_stat = cbind(colMeans(weight_mat), colSds(weight_mat), 1:tf)
biomass_stat = cbind(colSums(weight_mat),  1:tf)
Pexc_stat = cbind(colMeans(Pexc_mat), colSds(Pexc_mat),  1:tf)
Lexc_stat = cbind(colMeans(Lexc_mat), colSds(Lexc_mat))
Cexc_stat = cbind(colMeans(Cexc_mat), colSds(Cexc_mat))
Pwst_stat = cbind(colMeans(Pwst_mat), colSds(Pwst_mat),  1:tf)
Lwst_stat = cbind(colMeans(Lwst_mat), colSds(Lwst_mat))
Cwst_stat = cbind(colMeans(Cwst_mat), colSds(Cwst_mat))
ingvero_stat = cbind(colMeans(ingvero_mat), colSds(ingvero_mat))
anab_stat = cbind(colMeans(anab_mat), colSds(anab_mat))
catab_stat = cbind(colMeans(catab_mat), colSds(catab_mat))
O2_stat = cbind(colMeans(O2_mat), colSds(O2_mat))
NH4_stat = cbind(colMeans(NH4_mat), colSds(NH4_mat))
resource_stat = cbind(colSums(resource_mat),  1:tf)


biomass_df <- as.data.frame(biomass_stat) |> 
  rename(mean=V1, sd=V2, days=V3)



ggplot(data = biomass_df)+
  geom_ribbon(aes(x = days, ymin = mean-sd, ymax = mean+sd), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
  geom_line(aes(x = days, y = mean))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Biomass (tonnes)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))+
  scale_y_continuous(labels = \(y) y/1000000)


ggsave(filename = file.path(this_path, sprintf("figures/outputs/weight_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")


biomass_df <- as.data.frame(biomass_stat) |> 
  rename(biomass=V1, days=V2)



ggplot(data = biomass_df)+
  geom_line(aes(x = days, y = biomass/1000000))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Biomass (tonnes)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))


ggsave(filename = file.path(this_path, sprintf("figures/outputs/biomass_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")



Pexc_df <- as.data.frame(Pexc_stat) |> 
  rename(mean=V1, sd=V2, days=V3)



ggplot(data = Pexc_df)+
  geom_ribbon(aes(x = days, ymin = mean-sd, ymax = mean+sd), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
  geom_line(aes(x = days, y = mean))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Protein excretion (g)")+
  guides(alpha = "none", fill = "none", colour = "none")+
  theme(text=element_text(size=8))



ggsave(filename = file.path(this_path, sprintf("figures/outputs/Pexc_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")





Pwst_df <- as.data.frame(Pwst_stat) |> 
  rename(mean=V1, sd=V2, days=V3)



ggplot(data = Pwst_df)+
  geom_ribbon(aes(x = days, ymin = mean-sd, ymax = mean+sd), alpha = 0.2, fill = "salmon", colour = "grey50", linetype = "dashed")+
  geom_line(aes(x = days, y = mean))+
  theme_bw()+
  labs(x = "Production cycle (days)", y = "Protein waste from feed (g)")+
  theme(text=element_text(size=8))+



ggsave(filename = file.path(this_path, sprintf("figures/outputs/Pwst_%s.jpeg", this_farm_id)), dpi = 150, width = 12, height = 8, units="cm")




#stopCluster(cl)
  

output_labels <- c("weight", 
                   "protein_exc", "lipid_exc", "carb_exc",
                   "protein_wst", "lipid_wst", "carb_wst",
                   "ingvero", "anab", "catab", "O2", "NH4",
                   "resource", "fgt_mat", "frT_mat")


#test function
# this_df <- population_output[1]
# this_label <- output_labels[1]
  
map2(.x = population_output, .y = output_labels, \(this_df, this_label){
  
  this_df <- data.frame(this_df)
  rownames(this_df) <- 1:nrow(this_df)
  colnames(this_df) <- 1:tf
  
  qsave(x = this_df, file = file.path(Path, sprintf("data_products/large_files/%s_%s.qs", this_label, this_farm_id)))
  
})
 
  
  
  
  










```

 