---
title: "05_visualisation"
format: html
editor: source

execute:
  eval: false
  echo: false
  warning: false
  message: false
  cache: true
---

```{r setup, eval=T, cache=T}
library(tidyverse)
library(here)
library(ggpubr)
library(patchwork)
library(qs)
library(sf)
library(terra)
library(rnaturalearth)
library(rnaturalearthdata)
library(dtplyr)
library(future)
library(furrr)
library(RColorBrewer)

source("src/spatial_templates.R")
```

Rasterise reference feed data

REFERENCE FEED: Nitrogen per tonne

```{r}

reference_point_df<- qread(here("data/atlantic_salmon/data_products/model_summaries/reference/nitrogen_summary.qs")) |> 
  mutate(N_per_biomass_mean = total_N_mean/biomass_mean)


reference_feed_mean_N <- reference_point_df |> dplyr::select(geometry, N_per_biomass_mean) 

base_rast <- rast(res=1)
  
total_N_rast_ref <- rasterize(x = reference_feed_mean_N, y = base_rast, field = "N_per_biomass_mean", fun = mean)

total_N_rast_df_ref <- terra::as.data.frame(x= total_N_rast_ref, xy = TRUE)


#max values to scale legend nby 

total_N_rast_df_ref |> pull(mean) |> max()

# map nitrogen per tonne
reference_N_tonne <- ggplot()+
  geom_tile(data = total_N_rast_df_ref, aes(x = x, y = y, fill = mean))+
  geom_sf(data = ne_countries(scale = "large", returnclass = "sf"), colour = NA, fill = "grey95")+
  theme_void()+
   theme(legend.position = "bottom", 
        legend.title = element_text(size=10))+
  labs(subtitle = paste("Feed: reference"))+
  scale_fill_gradientn(colors = rev(brewer.pal(n = 9, name = "YlOrRd")), limits = c(0,0.8))+
  guides(fill = guide_colorbar(height = 0.1, unit = "in"))



#histogram

reference_hist <- ggplot()+
  geom_histogram(data = reference_point_df, aes(x = N_per_biomass_mean), fill = "darkgreen")+
  theme_pubr()+
  labs(subtitle = "Feed: plant-dominant")+
  scale_x_continuous(limits = c(-0.1, 1))


```

PAST FEED: Nitrogen per tonne

```{r}

past_point_df<- qread(here("data/atlantic_salmon/data_products/model_summaries/past/nitrogen_summary.qs")) |> 
  mutate(N_per_biomass_mean = total_N_mean/biomass_mean)


past_feed_mean_N <- past_point_df |> 
  dplyr::select(geometry, N_per_biomass_mean) 

base_rast <- rast(res=1)
  
total_N_rast_past <- rasterize(x = past_feed_mean_N, y = base_rast, field = "N_per_biomass_mean", fun = mean)

total_N_rast_df_past <- terra::as.data.frame(x= total_N_rast_past, xy = TRUE)

#max value for legend 
total_N_rast_df_past |> pull(mean) |> max()

#map nitrogen per tonne
past_N_tonne <- 
  ggplot()+
  geom_tile(data = total_N_rast_df_past, aes(x = x, y = y, fill = mean))+
  geom_sf(data = ne_countries(scale = "large", returnclass = "sf"), colour = NA, fill = "grey95")+
  theme_void()+
   theme(legend.position = "bottom", 
        legend.title = element_text(size=10))+
  labs(subtitle = paste("Feed: past"))+
  scale_fill_gradientn(colors = rev(brewer.pal(n = 9, name = "YlOrRd")), limits = c(0,0.8))+
  guides(fill = guide_colorbar(height = 0.1, unit = "in"))

#histogram of nitrogen per tonne

past_hist <- ggplot()+
  geom_histogram(data = past_point_df, aes(x = N_per_biomass_mean), fill = "darkblue")+
  theme_pubr()+
  labs(subtitle = "Feed: fish-dominant")+
  scale_x_continuous(limits = c(-0.1, 1))







```

FUTURE FEED: Nitrogen per tonne

```{r}

future_point_df<- qread(here("data/atlantic_salmon/data_products/model_summaries/future/nitrogen_summary.qs")) |> 
  mutate(N_per_biomass_mean = total_N_mean/biomass_mean)


future_feed_mean_N <- future_point_df |> 
  dplyr::select(geometry, N_per_biomass_mean) 

base_rast <- rast(res=1)
  
total_N_rast_future <- rasterize(x = future_feed_mean_N, y = base_rast, field = "N_per_biomass_mean", fun = mean)

total_N_rast_df_future <- terra::as.data.frame(x= total_N_rast_future, xy = TRUE)

#Map the per unit nitrogen

# max values to base legend off
total_N_rast_df_future |> pull(mean) |> max()

future_N_tonne <- 
  ggplot()+
  geom_tile(data = total_N_rast_df_future, aes(x = x, y = y, fill = mean))+
  geom_sf(data = ne_countries(scale = "large", returnclass = "sf"), colour = NA, fill = "grey95")+
  theme_void()+
  theme(legend.position = "bottom", 
        legend.title = element_text(size=10))+
  labs(subtitle = paste("Feed: future"))+
  scale_fill_gradientn(colors = rev(brewer.pal(n = 9, name = "YlOrRd")), limits = c(0,0.8))+
  guides(fill = guide_colorbar(height = 0.1, unit = "in"))
  
example_legend <- get_legend(future_N_tonne)


ggsave(filename = sprintf(here("explore/cottrell_explore/N_per_tonne_%s.jpg"), this_feed), dpi = 300, device = "jpg", width = 5, height =3)


#histogram of nitrogen per tonne



future_hist <- ggplot()+
  geom_histogram(data = future_point_df, aes(x = N_per_biomass_mean), fill = "firebrick4")+
  theme_pubr()+
  labs(subtitle = "Feed: novels-dominant")+
  scale_x_continuous(limits = c(-0.1, 1))






```

PLotting: Nitrogen per tonne

```{r}

# Maps of N per tonne
maps <- reference_N_tonne /
          past_N_tonne/
          future_N_tonne +
  plot_layout(ncol=1, 
              nrow = 3,
              guides = "collect") & 
  theme(legend.position = "bottom")


ggsave(filename = here("explore/cottrell_explore/N_per_tonne_all_feeds_maps.jpg"), dpi = 300, device = "jpg", width = 5, height =9)


hists <- reference_hist /
          past_hist/
          future_hist +
  plot_layout(ncol=1, 
              nrow = 3,
              guides = "collect") & 
  theme(legend.position = "bottom")
  

ggsave(filename = here("explore/cottrell_explore/N_per_tonne_all_feeds_hist.jpg"), dpi = 300, device = "jpg", width = 5, height =9)

```

REFERENCE FEED: Total nitrogen

```{r}


reference_point_df<- qread(here("data/atlantic_salmon/data_products/model_summaries/reference/nitrogen_summary.qs"))


reference_feed_total_N <- reference_point_df |> dplyr::select(geometry, total_N_mean) 

base_rast <- rast(res=1)
  
total_N_rast_ref <- rasterize(x = reference_feed_total_N, y = base_rast, field = "total_N_mean", fun = sum)

total_N_rast_df_ref <- terra::as.data.frame(x= total_N_rast_ref, xy = TRUE)


#max values to scale legend nby 

total_N_rast_df_ref |> pull(sum) |> max()

# map nitrogen per tonne
reference_total_N <- ggplot()+
  geom_tile(data = total_N_rast_df_ref, aes(x = x, y = y, fill = sum))+
  geom_sf(data = ne_countries(scale = "large", returnclass = "sf"), colour = NA, fill = "grey95")+
  theme_void()+
   theme(legend.position = "bottom", 
        legend.title = element_text(size=10))+
  labs(subtitle = paste("Feed: reference"))+
  scale_fill_gradientn(colors = rev(brewer.pal(n = 9, name = "YlOrRd")), limits = c(0,10000))+
  guides(fill = guide_colorbar(height = 0.1, unit = "in"))



#histogram

reference_point_df |> pull(total_N_mean) |> max()

reference_hist <- ggplot()+
  geom_histogram(data = reference_point_df, aes(x = total_N_mean), fill = "darkgreen")+
  theme_pubr()+
  labs(subtitle = "Feed: plant-dominant")+
  scale_x_continuous(limits = c(0, 270))+
  geom_vline(xintercept = median(reference_point_df$total_N_mean), linetype = "dashed")


```

PAST FEED: Total nitrogen

```{r}

past_point_df<- qread(here("data/atlantic_salmon/data_products/model_summaries/past/nitrogen_summary.qs"))


past_feed_total_N <- past_point_df |> 
  dplyr::select(geometry, total_N_mean) 

base_rast <- rast(res=1)
  
total_N_rast_past <- rasterize(x = past_feed_total_N, y = base_rast, field = "total_N_mean", fun = sum)

total_N_rast_df_past <- terra::as.data.frame(x= total_N_rast_past, xy = TRUE)

#max value for legend 
total_N_rast_df_past |> pull(sum) |> max()

#map total nitrogen
past_total_N <- 
  ggplot()+
  geom_tile(data = total_N_rast_df_past, aes(x = x, y = y, fill = sum))+
  geom_sf(data = ne_countries(scale = "large", returnclass = "sf"), colour = NA, fill = "grey95")+
  theme_void()+
   theme(legend.position = "bottom", 
        legend.title = element_text(size=10))+
  labs(subtitle = paste("Feed: past"))+
  scale_fill_gradientn(colors = rev(brewer.pal(n = 9, name = "YlOrRd")), limits = c(0,10000))+
  guides(fill = guide_colorbar(height = 0.1, unit = "in"))

#histogram of nitrogen per tonne

past_point_df |> pull(total_N_mean) |> max()

past_hist <- ggplot()+
  geom_histogram(data = past_point_df, aes(x = total_N_mean), fill = "darkblue")+
  theme_pubr()+
  labs(subtitle = "Feed: fish-dominant")+
  scale_x_continuous(limits = c(0,270))+
  geom_vline(xintercept = median(past_point_df$total_N_mean), linetype = "dashed")







```

FUTURE FEED: Total nitrogen

```{r}

future_point_df<- qread(here("data/atlantic_salmon/data_products/model_summaries/future/nitrogen_summary.qs")) 


future_feed_total_N <- future_point_df |> 
  dplyr::select(geometry, total_N_mean) 

base_rast <- rast(res=1)
  
total_N_rast_future <- rasterize(x = future_feed_total_N, y = base_rast, field = "total_N_mean", fun = sum)

total_N_rast_df_future <- terra::as.data.frame(x= total_N_rast_future, xy = TRUE)

#Map the per unit nitrogen

# max values to base legend off
total_N_rast_df_future |> pull(sum) |> max()

future_total_N <- 
  ggplot()+
  geom_tile(data = total_N_rast_df_future, aes(x = x, y = y, fill = sum))+
  geom_sf(data = ne_countries(scale = "large", returnclass = "sf"), colour = NA, fill = "grey95")+
  theme_void()+
  theme(legend.position = "bottom", 
        legend.title = element_text(size=10))+
  labs(subtitle = paste("Feed: future"))+
  scale_fill_gradientn(colors = rev(brewer.pal(n = 9, name = "YlOrRd")), limits = c(0,10000))+
  guides(fill = guide_colorbar(height = 0.1, unit = "in"))
  
example_legend <- get_legend(future_N_tonne)



#histogram of nitrogen per tonne

future_point_df |> pull(total_N_mean) |> max()

future_hist <- ggplot()+
  geom_histogram(data = future_point_df, aes(x = total_N_mean), fill = "firebrick4")+
  theme_pubr()+
  labs(subtitle = "Feed: novels-dominant")+
  scale_x_continuous(limits = c(0,270))+
  geom_vline(xintercept = median(future_point_df$total_N_mean), linetype = "dashed")






```

```{r}

# Maps of N per tonne
maps <- reference_total_N /
          past_total_N/
          future_total_N +
  plot_layout(ncol=1, 
              nrow = 3,
              guides = "collect") & 
  theme(legend.position = "bottom")


ggsave(filename = here("explore/cottrell_explore/total_N_all_feeds_maps.jpg"), dpi = 300, device = "jpg", width = 5, height =9)


hists <- reference_hist /
          past_hist/
          future_hist +
  plot_layout(ncol=1, 
              nrow = 3,
              guides = "collect") & 
  theme(legend.position = "bottom")
  

ggsave(filename = here("explore/cottrell_explore/total_N_all_feeds_hist.jpg"), dpi = 300, device = "jpg", width = 5, height =9)

```

#SPECIES IMPACTS

```{r}

east_canada_sp_impact <- qread("data/atlantic_salmon/data_products/spatial_summaries/all_regions.qs") |> filter(region == "East Canada") |> group_by(x,y) |> summarise(mean_impact = mean(impact, na.rm =TRUE))


ggplot()+
  geom_tile(data = east_canada_sp_impact, 
            aes(x = x, y = y, fill = mean_impact))+
  geom_sf(data = ne_countries(scale="medium", returnclass = "sf") |> st_crop(east_canada_bbox))+
  scale_fill_gradientn(colours = c("yellow", "orange", "red"))
  

ggsave("explore/cottrell_explore/east_canada_spp_impact.jpg", device= "jpg", dpi=300, width = 20, height = 10, units="cm")



west_canada_sp_impact <- qread("data/atlantic_salmon/data_products/spatial_summaries/all_regions.qs") |> filter(region == "West Canada") |> group_by(x,y) |> summarise(mean_impact = mean(impact, na.rm =TRUE))


ggplot()+
  geom_tile(data = west_canada_sp_impact, 
            aes(x = x, y = y, fill = mean_impact))+
  geom_sf(data = ne_countries(scale="medium", returnclass = "sf") |> st_crop(west_canada_bbox))+
  scale_fill_gradientn(colours = c("yellow", "orange", "red"))
  
ggsave("explore/cottrell_explore/west_canada_spp_impact.jpg", device= "jpg", dpi=300, width = 15, height = 10, units="cm")


europe_iceland_sp_impact <- qread("data/atlantic_salmon/data_products/spatial_summaries/all_regions.qs") |> filter(region == "Europe & Iceland") |> group_by(x,y) |> summarise(mean_impact = mean(impact, na.rm =TRUE))



ggplot()+
  geom_tile(data = europe_iceland_sp_impact, 
            aes(x = x, y = y, fill = mean_impact))+
  geom_sf(data = ne_countries(scale=50, returnclass = "sf", continent = "Europe") |> st_crop(europe_iceland_bbox), fill = "grey70")+
  scale_fill_gradientn(colours = c("yellow", "orange", "red"))
  

ggsave("explore/cottrell_explore/europe_iceland_spp_impact.jpg", device= "jpg", dpi=300, width = 17, height = 10, units="cm")




chile_sp_impact <- qread("data/atlantic_salmon/data_products/spatial_summaries/all_regions.qs") |> filter(region == "Chile") |> group_by(x,y) |> summarise(mean_impact = mean(impact, na.rm =TRUE))



ggplot()+
  geom_tile(data = chile_sp_impact, 
            aes(x = x, y = y, fill = mean_impact))+
  geom_sf(data = ne_countries(scale=50, returnclass = "sf") |> st_crop(chile_bbox), fill = "grey70")+
  scale_fill_gradientn(colours = c("yellow", "orange", "red"))
  
ggsave("explore/cottrell_explore/chile_spp_impact.jpg", device= "jpg", dpi=300, width = 12, height = 16, units="cm")



aus_sp_impact <- qread("data/atlantic_salmon/data_products/spatial_summaries/all_regions.qs") |> filter(region == "Australia") |> group_by(x,y) |> summarise(mean_impact = mean(impact, na.rm =TRUE))



ggplot()+
  geom_tile(data = aus_sp_impact, 
            aes(x = x, y = y, fill = mean_impact))+
  geom_sf(data = ne_countries(scale=50, returnclass = "sf") |> st_crop(australia_bbox), fill = "grey70")+
  scale_fill_gradientn(colours = c("yellow", "orange", "red"))+
  theme_bw()
  
ggsave("explore/cottrell_explore/tas_spp_impact.jpg", device= "jpg", dpi=300, width = 17, height = 10, units="cm")


```
