---
title: "03_combining temperature_data"
format: html
editor: visual
---


```{r}

library(tidyverse)
library(here)
library(terra)
library(sf)
library(qs)
library(tools)
library(tictoc)
library(future)
library(furrr)



source("src/dir.R")


```


```{r}

SST_files <- list.files("data/_general_data/SST/SST_rasters", full.names = TRUE)


this_day_SST <- SST_files[[1]]

temperature_df <- 
  map_df(.x = SST_files, .f = \(this_day_SST){
  
  day <- str_replace(file_path_sans_ext(this_day_SST), '.+day_(.+)', '\\1')
  
  message("Processing temperature data for day ", day)
  
  this_day_rast <- 
    as.data.frame(rast(this_day_SST), xy=TRUE) |> 
    mutate(day = day)
  
})


qsave(x = temperature_df, file = "data/_general_data/SST/SST_df.qs")

```

Joining farm location data to temperatures


```{r}

# gapfilling raster first


days <- seq(1:365)

for(day in days){
  
  init_rast <- rast(sprintf("data/_general_data/SST/SST_rasters/sst_nasa_mur_L4_0.25_mean2010-2019_day_%s.tif", day))
  
  gf_rast <- focal(init_rast, w = 5, na.policy = "only")
  
  
  
  
}


plot(init_rast)








farms <- qread(file = "data/_general_data/farm_locations/locations_w_species_fao_area.qs")

sst_rast <- rast("data/_general_data/SST/SST_rasters/sst_nasa_mur_L4_0.25_mean2010-2019_day_1.tif")

sst <- qread(file = "data/_general_data/SST/SST_df.qs")

farms_list <- 
  farms |> 
  select(-row_num) |> 
  mutate(farm_id = row_number()) |> 
  group_by(farm_id) |> 
  group_split(farm_id)


this_farm_id <- farms_list[[1]]
this_day = 1

#run in parallel
plan(strategy = "multisession", workers = parallel::detectCores()-2)


farm_list_w_temps <- 
  
  future_map(.x = farms_list, .f = \(this_farm_id){
  
  days <- seq(1:365)
  
  map_df(days, .f =\(this_day){
    
    message("Extracting temperature for farm ID ", this_farm_id$farm_id, ", day ",this_day)
    
    this_rast <- rast(list.files("data/_general_data/SST/SST_rasters/", pattern = paste0("day_", this_day, ".tif"), full.names = TRUE))
    
    temp <- extract(this_rast, this_farm_id)
    
    this_farm_id$mean_temp <- temp$mean
    
    return(this_farm_id)
    
  })
  }

)
 

qsave(farm_list_w_temps, file = "data/_general_data/farm_locations/locations_w_temps.qs")


```

