---
title: "Local to global N input modelling"
# Author roles: "writing – original draft", "writing – review & editing", "formal analysis", "funding acquisition", "conceptualization", "data curation", "investigation", "methodology", "project administration", "resources", "software", "supervision", "validation", "visualization"
author:
  - name: Tormey Reimer
    orcid: 0000-0002-5983-2798
    corresponding: true
    email: tormey.reimer@utas.edu.au
    role: 
      - methodology: supporting
      - analysis: lead
      - writing: lead
    affil-id: [1,2]
  - name: Richard S. Cottrell
    orcid: 0000-0002-6499-7503
    corresponding: false
    roles: 
      - conceptualization: lead
      - methodology: lead
      - writing: supporting
    # affil-id: [1,2]
  - name: Alexandra Johne
    orcid: 0000-0002-2816-7983
    corresponding: false
    roles: 
      - methodology: supporting
    affil-id: 3
  - name: Sowdamini Sesha Prasad
    # orcid: 
    corresponding: false
    roles: 
      - methodology: supporting
    # affil-id: [3,2]
  - name: Marceau Cormery
    # orcid: 
    corresponding: false
    roles: 
      - methodology: supporting
    # affil-id: [3,2]
  - name: Gage Clawson
    # orcid: 
    corresponding: false
    roles: 
      - methodology: supporting
    # affil-id: [3,2]
  - name: Scott Hadley
    # orcid: 
    corresponding: false
    roles: 
      - methodology: supporting
    # affil-id: [3,2]
  - name: Helen Hamilton
    # orcid: 
    corresponding: false
    roles: 
      - conceptualization: supporting
    # affil-id: [3,2]
  - name: Benjamin S. Halpern
    # orcid: 
    corresponding: false
    roles: 
      - conceptualization: supporting
    # affil-id: [3,2]
  - name: Catriona Macleod
    # orcid: 
    corresponding: false
    roles: 
      - conceptualization: supporting
    # affil-id: [3,2]
  - name: Camille White
    # orcid: 
    corresponding: false
    roles: 
      - conceptualization: supporting
    # affil-id: [3,2]
  - name: Julia L. Blanchard
    # orcid: 
    corresponding: false
    roles: 
      - conceptualization: supporting
      - methodology: supporting
      - analysis: supporting
      - editing: supporting
    # affil-id: [3,2]
    
affiliations:
  - id: 1
    name: Institute for Marine and Antarctic Studies
    group: Fisheries & Aquaculture
    address: 29 Nubeena Crescent
    city: Taroona
    region: TAS
    country: Australia
    postal-code: 7053
    url: https://www.imas.utas.edu.au/
  - id: 2
    name: Centre for Marine Socioecology
    url: https://marinesocioecology.org/
  - id: 1
    name: Institute for Marine and Antarctic Studies
    group: Ecology & Biodiversity
    # address: 29 Nubeena Crescent
    # city: Taroona
    # region: TAS
    # country: Australia
    # postal-code: 7053
    url: https://www.imas.utas.edu.au/
  # - id: 3
  #   name: Heriott-Watt University, Institute for Life and Earth Sciences
  #   department: School of Energy, Geoscience, Infrastructure and Society
  #   address: Franklin Road
  #   city: Stromness
  #   region: Orkney
  #   country: United Kingdom
  #   postal-code: KW16 3AN
  #   url: https://www.hw.ac.uk/
# keywords:
#   - keyword
#   - keyword
# abstract: |
#   Any new aquaculture venture...
# plain-language-summary: |
#   Plain language summary goes here....
# key-points:
#   - Point 1
#   - Point 2
bibliography: ["../resources/refs.bib", "../resources/manual-refs.bib"]

format: 
  html:
    theme: simplex
    css: ["../resources/extra.css"]
    code-fold: true
    code-overflow: wrap
    toc: true
    toc-expand: true
    toc-location: left
    lang: en-GB
    grid:
      sidebar-width: 350px
      body-width: 1200px
      margin-width: 250px
      gutter-width: 2em
  pdf:
    papersize: a4
    linestretch: 1.15
    link-citations: true
    keep-tex: true
    template-partials:
      - "../resources/title.tex"
    include-in-header:
      file: "../resources/header_extra.tex"

filters:
  - acronyms
  
execute:
  eval: true
  echo: false
  warning: false
  message: false
  cache: true
  
knitr: 
  opts_chunk:
    fig.align: center

editor: source
---

```{r setup}
#| include: false
#| cache: false
#| eval: true

library(magrittr)
library(dplyr)
library(tidyr)
library(stringr)
library(ggplot2)
library(here)
library(ggpubr)
library(patchwork)
library(qs)
library(arrow)
library(targets)
library(sf)
library(terra)
library(rnaturalearth)
library(rnaturalearthdata)
library(dtplyr)
library(furrr)
library(RColorBrewer)
library(purrr)
library(future)
library(readxl)
library(units)
library(conflicted)
library(lubridate)
conflicts_prefer(dplyr::select(), dplyr::filter(), dplyr::intersect(), .quiet = T)
# This markdown uses TinyTex - install with tinytex::install_tinytex()
```

# Introduction

Aquaculture is now the dominant form of aquatic animal food (herein ‘seafood’) production and is expected to be the primary way we meet future seafood demand. Freshwater systems will likely continue to provide the majority of farmed seafood but marine aquaculture is also poised to expand substantially in numerous areas. Farmed marine fish and invertebrates are produced near exclusively in coastal waters, and nearly three quarters of this production is dependent on human-made feeds. Nearshore locations and feed inputs are necessary to maintain profitable and productive farming operations but coastal aquaculture generates a number of challenges. In the crowded coastal zone, aquaculture operations can conflict with other stakeholder uses such as recreation, fishing, renewable energy, transport, and tourism. 
And while farming marine fish typically generates a far smaller nutrient footprint than livestock farming, the overt nature of aquaculture in nearshore regions and evidence of  localised nutrient impacts around fish farms remains a primary public and scientific concern. Identifying strategies that reduce ecosystem impacts from fish farm waste therefore represents an important goal for improving marine aquaculture sustainability and maintaining the sector’s social licence to operate. 

Aquaculture feeds represent an important lever for reducing nutrient waste impacts around fish farms. Like all farmed animals, fish and invertebrates must digest the nutrients contained in feeds before they can be used for growth. Any nutrients left undigested are egested as solid waste, and dissolved wastes are excreted as metabolic waste products. Further, some feed inevitably remains uneaten and is lost to the surrounding ecosystem. Particulate organic matter (both feed and faeces) that settles can simplify benthic communities as the oxygen demand from its decomposition drives the production of sulphides that kill less mobile faunal, encouraging a lower diversity of opportunistic scavengers and the growth of bacterial mats (e.g., Beggiatoa spp). Thus, the chemical composition of the ingredients used in aquaculture feeds and their digestibility for the farmed species has significant implications for the nature and reactivity of the waste generate by marine aquaculture.

Firstly the overall volume of nutrient waste is dictated by the nature and intensity of production, that is the farm size, the density of farmed animals and the feed requirements and efficiency of the species grown. SecondlDeposition of waste is heavily influenced by water depth and current speed at the farming site. Once

As farmed fish and invertebrates are fed, whatever	

Nutand its impact on marine ecosystems is influenced by many factors. 
* Farm size
* Depth
* Current speed
* Benthic impact - sediment type/faunal assemblages/wider marine community
* High turnover environments - nitrogen enriched areas
* Feed influences all of these things

The primary source of organic waste from fed aquaculture production comes from the excretion and faeces of the farmed animals and through uneaten feed that dissolves in the water column or settles on the benthos. The nature and impact of this waste are influenced heavily by the composition of the feeds fed to farmed animals. 

## P2

* Waste from aquaculture farms and it’s impact is influenced by many things but the composition of feeds plays a central role.
* Waste from aquaculture farms has multiple sources. 
* The primary source of organic waste comes from the faeces and excretion of the fish or invertebrates.
* Uneaten feed produced another key source.
* The nature and impact of this waste are influenced heavily by the composition of the feeds fed to farmed animals
* Many marine fish are naturally carnivorous so diets used to be high in fishmeal and oil but increasing fishmeal and oil prices along with concerns over the sustainability of marine ingredients have led to a reduction in their use across multiple farmed taxa
* In lieu of fishmeal and oil, many plant-based ingredients such as soy protein concentrate, canola oil, and wheat gluten have replaced them. 
* Changes in feed composition influences the digestibility of the nutrients held in each feed and can alter the composition of waste.
* Of particular concern are changes (increases) to the presence of reactive nitrogen and phosphorus in coastal waters that could have an effect on eutrophication. 

## P3

* Whether or not nutrients lead to eutrophication depends on the sensitivity of the receiving environment
* Ecosystems that are already enriched through natural processes and whose biota is well adapted to substantial fluxes in available nutrients (e.g. upwelling zones, dynamic coastal communities) may be less sensitive while oligotrophic ecosystem are likely to see considerable changes under nutrient enrichment scenarios.
* To understand the impact of aquaculture waste under present day or future scenarios we need to quantify the volume, nature, and location of mariculture waste and determine the sensitivity of the receiving environments to that waste. Yet only recent estimates even give us the estimated location of marine farms let alone the volume of nature of the waste produced.
To address this gap, we use existing maps of mariculture location with a bioenergtic model

# Statistical analysis

All analysis was conducted in R version `r R.version[['minor']]` "`r R.version[['nickname']]`" [@R_base]. 

# Code availability

This manuscript was written in Quarto [@quarto] using TinyTex [@tinytex] and the acronyms extension [@acronyms]. 
For a full list of R packages used see the [lockfile](https://www.github.com).



